[programs.localnet]
mysolanaapp = "7UTxoNfZk8BwksF443KtfsYVcKdTa8xYRqFnutWSHi6j"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/chirag/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
